create table users (
    id SERIAL PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    isShopOwner BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP
    WITH
        TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMP
    WITH
        TIME ZONE DEFAULT CURRENT_TIMESTAMP
);